{% set name = "smokescreen" %}
{% set version = "1.5.0" %}
{% set python_min = "3.12" %}

package:
  name: lsstdesc-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smokescreen-{{ version }}.tar.gz
  sha256: 22f89159b692fe9f847fc8ea46d068147875144db1dce7e9fce31a2f4d561b9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.2.0
    - scipy >=1.9.0
    - astropy-base >=5.3.0
    - sacc >=0.12
    - pyccl >=3.0.2
    - jsonargparse >=4.0
    - cosmosis >=2.5
    - fitsio
    - firecrown
    - cosmosis-build-standard-library

test:
  imports:
    - smokescreen
  requires:
    - python {{ python_min }}
  # no pip check since it is broken
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/LSSTDESC/Smokescreen
  summary: 'Smokescreen: DESC Blinding Unified Library. Based on the Muir et al. (2021) data-vector blinding method.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - arthurmloureiro
