{% set name = "smokescreen" %}
{% set version = "1.5.6" %}
{% set python_min = "3.12" %}

package:
  name: lsstdesc-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smokescreen-{{ version }}.tar.gz
  sha256: 6175764dc52f6d2758691e9be42f39ccbde9b5c700f89d6989ad078c09a44584

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.2.0
    - scipy >=1.9.0
    - astropy-base >=5.3.0
    - sacc >=0.12
    - pyccl >=3.0.2
    - jsonargparse >=4.0
    - typeshed-client
    - cosmosis >=2.5
    - fitsio
    - firecrown
    - cryptography
    - cosmosis-build-standard-library

test:
  imports:
    - smokescreen
  requires:
    - python {{ python_min }}
  # no pip check since it is broken
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/LSSTDESC/Smokescreen
  summary: 'Smokescreen: DESC Blinding Unified Library. Based on the Muir et al. (2021) data-vector blinding method.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - arthurmloureiro
